# NodePort service for study designer server.
apiVersion: v1
kind: Service
metadata:
  name: study-designer-np
spec:
  type: NodePort
  selector:
    app: study-designer
  ports:
  - protocol: TCP
    port: 50000
    targetPort: 8080
