included:
  - MyStudies
disabled_rules:
  - type_body_length
  - function_body_length
  - trailing_whitespace
  - force_cast
  - trailing_comma
  - nesting
  - cyclomatic_complexity
  - file_length
  - todo
  - opening_brace
  - redundant_string_enum_value
  - class_delegate_protocol
  - weak_delegate
  - legacy_constructor
  - multiple_closures_with_trailing_closure
  - identifier_name
  - leading_whitespace
  - colon
  - closure_parameter_position
  - type_name
  - large_tuple 
line_length:
  ignores_interpolated_strings: true
  ignores_comments: true
  warning: 140
  error: 150
function_parameter_count:
  warning: 8
  error: 8
