import {Study} from '../site-coordinator/studies/shared/study.model';

export const expectedStudyList = [
  {
    appId: '',
    appInfoId: 0,
    customId: 'NewStudyTest',
    enrolledCount: 41,
    enrollmentPercentage: 38,
    id: 1,
    invitedCount: 0,
    name: 'New Study Test',
    sites: [],
    studyPermission: 0,
    totalSitesCount: 16,
    type: 'OPEN',
    logo: '/path_to_img/',
  },
  {
    appId: '',
    appInfoId: 0,
    customId: 'OpenStudy',
    enrolledCount: 5,
    enrollmentPercentage: 0,
    id: 12,
    invitedCount: 9,
    name: 'Open Study 02',
    sites: [],
    studyPermission: 1,
    totalSitesCount: 5,
    type: 'OPEN',
    logo: '/path_to_img/',
  },
  {
    appId: '',
    appInfoId: 0,
    customId: 'ClosedStudy',
    enrolledCount: 54,
    enrollmentPercentage: 17,
    id: 14,
    invitedCount: 0,
    name: 'Closed Study',
    sites: [],
    studyPermission: 2,
    totalSitesCount: 6,
    type: 'CLOSE',
    logo: '/path_to_img/',
  },
] as Study[];
