project_id                = "heroes-hat-dev-apps"
network_project_id        = "heroes-hat-dev-networks"
gke_region                = "us-east1"
repo_owner                = "GoogleCloudPlatform"
repo_name                 = "fda-mystudies"
cloudbuild_trigger_branch = "early-access"
