export const environment = {
  production: true,
  participantManagerDatastoreUrl: '',
  baseHref: '/',
  hydraLoginUrl: '',
  authServerUrl: '',
  authServerRedirectUrl: '',
  hydraClientId: '',
  appVersion: '',
  termsPageTitle: 'terms title goes here',
  termsPageDescription: 'terms description goes here',
  aboutPageTitle: 'about page title goes here',
  aboutPageDescription: 'about page description goes here',
  copyright: 'Copyright 2020 Google LLC.',
};
