apiVersion: v1
kind: Service
metadata:
  name: study-meta-data-np
  # Add Container Native Load Balancing.
  # See https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#create_service
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates a NEG after an Ingress is created
spec:
  type: NodePort
  selector:
    app: study-meta-data
  ports:
  - protocol: TCP
    port: 50000
    targetPort: 8080
