apiVersion: v1
kind: Service
metadata:
  name: user-registration-server-np
spec:
  type: NodePort
  selector:
    app: user-registration-server
  ports:
  - protocol: TCP
    port: 50000
    targetPort: 8080
