apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-registration-server-ws
  labels:
    app: user-registration-server-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-registration-server
  template:
    metadata:
      labels:
        app: user-registration-server
    spec:
      containers:
        - name: user-registration-ws
          image: gcr.io/heroes-hat-dev-apps/user-registration-server-ws:latest
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-registration-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: user-registration-db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: user-registration-db-credentials
                  key: dbname
            - name: FROM_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_address
            - name: FROM_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_password
            - name: AUTH_SERVER_URL
              value: "auth-server-np:50000"
            - name: RESPONSE_SERVER_URL
              value: "response-server-np:50000"
            - name: CLIENT_ID
              value: "test_client_id_urs"
            - name: SECRET_KEY
              value: "dummy-value"
            - name: GCP_BUCKET_NAME
              value: "heroes-hat-dev-data-my-study-consent-documents"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/gcloud_key/key.json"
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /myStudiesUserMgmtWS/healthCheck
              port: 8080
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command: ["/cloud_sql_proxy",
            "-instances=heroes-hat-dev-data:us-east1:my-studies-2=tcp:3306",
            "-credential_file=/secrets/gcloud_key/key.json"]
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
      volumes:
      - name: gcloud-key-volume
        secret:
          secretName: user-registration-gcloud-key
