apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-manager
  labels:
    app: participant-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participant-manager
  template:
    metadata:
      labels:
        app: participant-manager
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        # application container
        - name: user-registration-ws
          image: gcr.io/fda-mystudies-dev-apps/participant-manager:latest
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/gcloud_key/key.json"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: participant-manager-db-credentials
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: participant-manager-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: participant-manager-db-credentials
                  key: password
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: participant-manager-secrets
                  key: CLIENT_ID
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: participant-manager-secrets
                  key: SECRET_KEY
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: participant-manager-secrets
                  key: BASE_URL
            - name: GCP_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: participant-manager-secrets
                key: GCP_BUCKET_NAME
            # email configs
            - name:  MAIL_PROTOCOL
              value: smtp
            - name: MAIL_HOST
              value: smtp.gmail.com
            - name: MAIL_PORT
              value: 465
            - name: MAIL_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_address
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_address
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: email_password
            - name: MAIL_CONTACT_EMAIL
              value: ""

          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /participant-manager-service/healthCheck
              port: 8080
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
        # sidecar container
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command: ["/cloud_sql_proxy",
            "-instances=fda-mystudies-dev-data:us-east1:mystudies=tcp:3306",
            "-credential_file=/secrets/gcloud_key/key.json"]
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
      volumes:
      - name: gcloud-key-volume
        secret:
          secretName: participant-manager-gcloud-key
