//  Copyright 2020 Google LLC
//
//  Use of this source code is governed by an MIT-style
//  license that can be found in the LICENSE file or at
//  https://opensource.org/licenses/MIT.

import Foundation

enum Branding {

  private enum JSONKey {
    static let joinStudyButtonTitle = "JoinStudyButtonTitle"
    static let viewConsentButtonTitle = "ViewConsentButtonTitle"
    static let visitWebsiteButtonTitle = "VisitWebsiteButtonTitle"
    static let consentPDF = "ConsentPDF"
    static let leaveStudy = "LeaveStudy"
    static let leaveStudyConfirmationText = "LeaveStudyConfirmationText"
    static let websiteLink = "WebsiteLink"
    static let websiteButtonTitle = "WebsiteButtonTitle"
    static let termsAndConditionURL = "TermsAndConditionURL"
    static let privacyPolicyURL = "PrivacyPolicyURL"
    static let validatedTitle = "ValidatedTitle"
    static let allowFeedback = "AllowFeedback"
    static let navigationTitleName = "NavigationTitleName"
    static let poweredByTitleName = "PoweredByTitleName"
    static let productTitleNAme = "ProductTitleName"
    static let isStandaloneStudyApp = "IsStandaloneStudyApp"
    static let standaloneStudyID = "StandaloneStudyId"
    static let appleID = "appleId"
  }

  private static var brandConfig: JSONDictionary {
    var nsDictionary: NSDictionary?
    if let path = Bundle.main.path(forResource: "Branding", ofType: "plist") {
      nsDictionary = NSDictionary(contentsOfFile: path)
    }
    return nsDictionary as? JSONDictionary ?? [:]
  }

  static var joinStudyButtonTitle: String {
    return brandConfig[JSONKey.joinStudyButtonTitle] as? String ?? ""
  }

  static var viewConsentButtonTitle: String {
    return brandConfig[JSONKey.viewConsentButtonTitle] as? String ?? ""
  }

  static var visitWebsiteButtonTitle: String {
    return brandConfig[JSONKey.visitWebsiteButtonTitle] as? String ?? ""
  }

  static var consentPDFTitle: String {
    return brandConfig[JSONKey.consentPDF] as? String ?? ""
  }

  static var leaveStudyTitle: String {
    return brandConfig[JSONKey.leaveStudy] as? String ?? ""
  }

  static var websiteLink: String {
    return UserManageApps.appDetails?.appWebsite ?? brandConfig[JSONKey.websiteLink] as? String ?? ""
  }

  static var websiteButtonTitle: String {
    return brandConfig[JSONKey.websiteButtonTitle] as? String ?? Branding.websiteLink
  }

  static var termsAndConditionURL: String {
    return UserManageApps.appDetails?.termsUrl ?? brandConfig[JSONKey.termsAndConditionURL] as? String ?? ""
  }

  static var privacyPolicyURL: String {
    return UserManageApps.appDetails?.privacyPolicyUrl ?? brandConfig[JSONKey.privacyPolicyURL] as? String ?? ""
  }

  static var validatedTitle: String {
    return brandConfig[JSONKey.validatedTitle] as? String ?? ""
  }

  static var allowFeedback: Bool {
    return brandConfig[JSONKey.allowFeedback] as? Bool ?? true
  }

  static var navigationTitleName: String {
    return brandConfig[JSONKey.navigationTitleName] as? String ?? ""
  }

  static var poweredByTitleName: String {
    return brandConfig[JSONKey.poweredByTitleName] as? String ?? ""
  }

  /// AppName
  static var productTitle: String {
    return brandConfig[JSONKey.productTitleNAme] as? String ?? ""
  }

  /// Boolean indicates wheather the current App is build as standalone App.
  static var isStandaloneStudyApp: Bool {
    return brandConfig[JSONKey.isStandaloneStudyApp] as? Bool ?? false
  }

  /// Study ID for standalone App.
  static var standaloneStudyID: String {
    return brandConfig[JSONKey.standaloneStudyID] as? String ?? ""
  }

  /// Unique ID of the App generated by Apple on AppStore Connect.
  /// Eg :- 2220229784
  static var appleID: String? {
    return brandConfig[JSONKey.appleID] as? String
  }

}
