apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-consent-datastore
  labels:
    app: participant-consent-datastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: participant-consent-datastore
  template:
    metadata:
      labels:
        app: participant-consent-datastore
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: participant-consent-datastore
          image: gcr.io/mystudies-dev-apps/participant-consent-datastore:latest
          env:
            # DB ACCESS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: participant-consent-datastore-credentials
                  key: dbusername
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: participant-consent-datastore-credentials
                  key: dbpassword
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: participant-consent-datastore-credentials
                  key: dbname
            # AUTHENTICATION
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: participant-consent-datastore-credentials
                  key: client_id
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: participant-consent-datastore-credentials
                  key: secret_key
            # SERVER CALLS
            - name: HYDRA_ADMIN_URL
              value: "http://hydra-np:4445"
            # MISC
            - name: GCP_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: gcp_bucket_name
            - name: LOG_PATH
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: log_path
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/gcloud_key/key.json"
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /participant-consent-datastore/healthCheck
              port: 8080
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command: ["/cloud_sql_proxy",
            "-instances=fda-mystudies-dev-data:us-east1:mystudies=tcp:3306",
            "-credential_file=/secrets/gcloud_key/key.json"]
          volumeMounts:
          - name: gcloud-key-volume
            mountPath: /secrets/gcloud_key
            readOnly: true
      volumes:
      - name: gcloud-key-volume
        secret:
          secretName: participant-consent-datastore-gcloud-key
