apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fda-mystudies-dev
  annotations:
    kubernetes.io/ingress.global-static-ip-name: mystudies-ingress-ip
    networking.gke.io/managed-certificates: fda-mystudies-cert
spec:
  rules:
    - http:
        paths:
          - path: /oauth-scim-module/*
            backend:
              serviceName: auth-server-np
              servicePort: 50000
          - path: /mystudies-response-server/*
            backend:
              serviceName: response-server-np
              servicePort: 50000
          - path: /myStudiesUserMgmtWS/*
            backend:
              serviceName: participant-datastore-user-np
              servicePort: 50000
          - path: /myStudiesConsentMgmtWS/*
            backend:
              serviceName: participant-datastore-consent-np
              servicePort: 50000
          - path: /myStudiesEnrollmentMgmt/*
            backend:
              serviceName: participant-datastore-enroll-np
              servicePort: 50000
          - path: /StudyMetaData/*
            backend:
              serviceName: study-meta-data-np
              servicePort: 50000
          - path: /studybuilder/*
            backend:
              serviceName: study-designer-np
              servicePort: 50000
          - path: /fdaResources/*
            backend:
              serviceName: study-designer-np
              servicePort: 50000
          - path: /hydra/*
              backend:
                serviceName: hydra-np
                servicePort: 4444
