# Copyright 2020 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
apiVersion: v1
kind: Service
metadata:
  name: participant-manager-datastore-np
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates a NEG after an Ingress is created
spec:
  type: NodePort
  selector:
    app: participant-manager-datastore
  ports:
  - protocol: TCP
    port: 50000
    targetPort: 8080
