export const commonusePassword: string[] = [
  'Pasword',
  'P@sword',
  'Qwerty',
  'Eagles',
  'Bears',
  'Giants',
  'Cowboy',
  'Vikings',
  'Chelsea',
  'Arsenal',
  'Manchesterunited',
  'Participantmanager',
  'Rams',
  'Lions',
  'Panthers',
  'Jaguars',
  'Texans',
  'GoPatriots',
  'Winter',
  'Minecraft',
  'Master',
  'Shadow',
  'Monkey',
  'US city name',
  'Country name',
  'US State name',
];
