on:
  pull_request:
    paths:
    - 'common-modules/**'
    - 'response-server-module/**'
    - '.github/workflows/build-response-server-module.yml'
name: Build-response-server-module
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
          cd response-server-module
          mvn -B package --file pom.xml
