name: Build-response-datastore
on:
  pull_request:
    paths:
    - 'common-modules/**'
    - 'response-datastore/**'
    - '.github/workflows/build-response-datastore.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: |
          cd response-datastore
          mvn -B package --file pom.xml
