on:
  pull_request:
    paths:
    - 'user-registration-server-ws/user-mgmt-module/**'
    - '.github/workflows/build-user-registration-server-user-mgmt-module.yml'
name: Build user-registration-server-ws-user-mgmt-module
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
          cd user-registration-server-ws/user-mgmt-module
          mvn -B package --file pom.xml
