on:
  pull_request:
    paths:
    - 'common-modules/**'
    - 'oauth-scim-module/**'
    - '.github/workflows/build-oauth-scim-module.yml'
name: Build-oauth-scim-module
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
          cd oauth-scim-module
          mvn -B package --file pom.xml        
