name: Build study datastore
on:
  pull_request:
    paths:
    - 'study-datastore/**'
    - '.github/workflows/build-study-datastore.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: |
          cd study-datastore
          mvn -B package --file pom.xml
