on:
  pull_request:
    paths:
    - 'common-modules/**'
    - 'participant-manager-module/**'
    - '.github/workflows/build-participant-manager-module.yml'
name: Build-participant-manager-module
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
          cd participant-manager-module
          mvn -B package --file pom.xml        
