name: user-mgmt-checkstyle

on: [pull_request]
    paths:
    - 'user-registration-server-ws/user-mgmt/**'
    - '.github/workflows/lint-user-mgmt.yml'

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /user-registration-server-ws/user-mgmt
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        level: error
        workdir: ./user-registration-server-ws/user-mgmt