name: Sonar Qube
on:
  pull_request:
    paths:
    - 'common-modules/**'
    - 'participant-manager-datastore/**'
    - '.github/workflows/build-participant-manager-datastore.yml'
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        projectBaseDir: "participant-manager-datastore/"
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
