name: Sonar Qube
on: 
 pull_request:
  paths:
    - 'study-builder/fdahpStudyDesigner/**'
    - '.github/workflows/build-studybuilder.yml'
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
