name: Sonar Qube
on:
  pull_request:
    paths:
    - 'common-modules/**'
    - 'participant-manager-datastore/**'
    - '.github/workflows/build-participant-manager-datastore.yml'
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        args: >
         -Dsonar.exclusions= "*.java"
         
        
